//
//  ItemsListPresenter.swift
//  TODOListWithSorts
//
//  Created by Vyacheslav Okulov on 1/16/17.
//  Copyright (c) 2017 Vyacheslav Okulov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ItemsListPresenterInput {
  func presentItems(response: ItemsList.Response)
}

protocol ItemsListPresenterOutput: class {
    func displayItems(viewModel:ItemsList.ViewModel)
}

class ItemsListPresenter: ItemsListPresenterInput {
  weak var output: ItemsListPresenterOutput!
  fileprivate lazy var dateFormatter = DateFormatter()
  // MARK: - Presentation logic
  
  func presentItems(response: ItemsList.Response) {
    // NOTE: Format the response from the Interactor and pass the result back to the View Controller
    
    let viewModel = ItemsList.ViewModel(itemsToShow:convertItemsToShowItems(items: response.todoItems))
    output.displayItems(viewModel: viewModel)
  }
    
    
}

private extension ItemsListPresenter {
    func convertItemsToShowItems(items:[TodoItem]) -> [ItemsListShowData] {
        var result = [ItemsListShowData]()
        for item in items {
           result.append(convertItemToShowItem(item: item))
        }
        return result
    }
    
    func convertItemToShowItem(item:TodoItem) -> ItemsListShowData {
        dateFormatter.dateFormat = "dd/MM/yyyy"
        let formattedDate = dateFormatter.string(from: item.date)
        let colorString = item.priority.colorString()
        
        return ItemsListShowData(title: item.title, date: formattedDate, colorString: colorString)
    }
    
    
}
