//
//  ItemsListViewController.swift
//  TODOListWithSorts
//
//  Created by Vyacheslav Okulov on 1/16/17.
//  Copyright (c) 2017 Vyacheslav Okulov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ItemsListViewControllerInput {
    func displayItems(viewModel:ItemsList.ViewModel)
}

protocol ItemsListViewControllerOutput {
  func loadAndShowAllItems()
}

class ItemsListViewController: UIViewController, ItemsListViewControllerInput {
  var output: ItemsListViewControllerOutput!
  var router: ItemsListRouter!
    
  //MARK: - Outlets
    
  @IBOutlet weak var tableView: UITableView!
   
  
  // MARK: - Object lifecycle
  
  override func awakeFromNib() {
    super.awakeFromNib()
    ItemsListConfigurator.sharedInstance.configure(viewController: self)
  }
  
  // MARK: - View lifecycle
  
  override func viewDidLoad() {
    super.viewDidLoad()
    configureTableView()
    output.loadAndShowAllItems()
  }
  
  // MARK: - Event handling
    
  // MARK: - Display logic
  
   func displayItems(viewModel:ItemsList.ViewModel) {
        
   }
}

private extension ItemsListViewController {
    func configureTableView() {
        tableView.delegate = self
        tableView.dataSource = self
    }
}

