//
//  ItemsListModels.swift
//  TODOListWithSorts
//
//  Created by Vyacheslav Okulov on 1/16/17.
//  Copyright (c) 2017 Vyacheslav Okulov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct ItemsList {
    struct ViewModel {
        let itemsToShow:[ItemsListShowData]
    }
    struct Request {
    }
    struct Response {
        let todoItems:[TodoItem]
    }
}
