//
//  ItemsListInteractor.swift
//  TODOListWithSorts
//
//  Created by Vyacheslav Okulov on 1/16/17.
//  Copyright (c) 2017 Vyacheslav Okulov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ItemsListInteractorInput {
    func loadAndShowAllItems()
}

protocol ItemsListInteractorOutput {
    func presentItems(response: ItemsList.Response)
}

class ItemsListInteractor: ItemsListInteractorInput {
  var output: ItemsListInteractorOutput!
  var worker: ItemsListWorker!
  
  // MARK: - Business logic
  func loadAndShowAllItems() {
    
    worker = ItemsListWorker()
    worker.doSomeWork()
    
    // NOTE: Pass the result to the Presenter
    
    let response = ItemsList.Response(todoItems:[TodoItem]())
    output.presentItems(response: response)
  }

}
