//
//  ItemsListConfigurator.swift
//  TODOListWithSorts
//
//  Created by Vyacheslav Okulov on 1/16/17.
//  Copyright (c) 2017 Vyacheslav Okulov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension ItemsListViewController: ItemsListPresenterOutput {
  override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
    router.passDataToNextScene(segue: segue)
  }
}

extension ItemsListInteractor: ItemsListViewControllerOutput {
}

extension ItemsListPresenter: ItemsListInteractorOutput {
}

class ItemsListConfigurator {
  // MARK: - Object lifecycle
  
  static let sharedInstance = ItemsListConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: ItemsListViewController) {
    let router = ItemsListRouter()
    router.viewController = viewController
    
    let presenter = ItemsListPresenter()
    presenter.output = viewController
    
    let interactor = ItemsListInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
